version: 1.0.{build}

image: Visual Studio 2019

before_build:
    - dotnet restore ".\src\TorrentExtractor.sln"

build_script:
    - dotnet build ".\src\TorrentExtractor.sln"

test_script:
    - dotnet test ".\src\TorrentExtractor.sln"
    
after_build:   
    - dotnet publish  ".\src\TorrentExtractor.Qbittorrent.ConsoleApp\TorrentExtractor.Qbittorrent.ConsoleApp.csproj" -c release -r win10-x64
    
artifacts:
    - path: .\src\TorrentExtractor.Qbittorrent.ConsoleApp\bin\release\netcoreapp3.1\win10-x64\publish